# Generated by Django 2.2.26 on 2022-05-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_projectapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
