# Generated by Django 2.2.26 on 2022-05-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_healthyapi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demoapi',
            options={'verbose_name': '首页上三大统计'},
        ),
        migrations.AlterModelOptions(
            name='healthyapi',
            options={'verbose_name': '膳食营养目标'},
        ),
    ]
